kubeconfig = ""
kubehost = "0.0.0.0"
backendurl = "http://10.25.1.15:15528"
kubenamespace = "default"
timeout = 20 # in seconds

[cluster]
deploymentlabel = "katana"
teamcount = 2
teamlabel = "ctfteam"
templated_manifest_dir = "kubernetes/templates"
templated_manifests = [
    "storage-init.yml", # should be first and always present
    "gogs.yml",
    "mysql.yml",
    "mongo.yml",
    "harbor.yml",
]

[services.api]
host = "0.0.0.0"
port = 15528

[teamvm]
teampodname = "katana-team-master-pod"
containername = "teamvm"
challengedir = "/opt/challenges/"
tmpdir = "/tmp/"
initfile = "run.sh"
daemonport = 3004

[services.sshprovider]
host = "0.0.0.0"
port = 2222
creds_file = "teamcreds.txt"
password_length = 10

[mongo]
username = "adminuser"
password = "password123"
port = "32000"
mongosh_version = "1.6.1"

[mysql]
username = "root"
password = "test1234"
port = "32001"

[admin]
username = "sdslabs"
password = "sdslabs"

[harbor]
username = "admin" # cannot be changed
password = "Password12345" # NOTE: Password should be 8-128 characters long with at least 1 uppercase, 1 lowercase and 1 number
