kubeconfig = ""
kubehost = "http://localhost"
backendurl = "http://192.168.49.1"
kubenamespace = "default"
verbosity = 3

[cluster]
deploymentlabel = "katana"
broadcastcount = 2
broadcastlabel = "broadcast"
teamcount = 2
teamlabel = "ctfteam"
manifest_dir = "manifests/templates"
manifests = [
    "broadcast.yml",
    "broadcast-service.yml",
    "ingress.yml",
    "openvpn.yml",
    "mysql.yml",
    "logs.yml",
    "mongo.yml",
    "gogs.yml",
]

[services.api]
host = "localhost"
port = 3000

[services.challengedeployer]
host = "challengedeployer.katana.local"
port = 8002
broadcastport = 3003
teamclientport = 3004
challengeartifactlabel = "challfile"

[teamvm]
teampodname = "katana-team-master-pod"
containername = "teamvm"
challengedir = "/opt/challenges/"
tmpdir = "/tmp/"
initfile = "run.sh"
daemonport = 3004

[services.sshprovider]
host = "0.0.0.0"
port = 2222
creds_file = "teamcreds.txt"
password_length = 10

[mongo]
username = "adminuser"
password = "password123"
port = "32000"
mongosh_version = "1.6.1"
cluster_url = "challengedeployer.katana.local"

[mysql]
username = "root"
password = "test1234"
port = "32001"

[admin]
username = "sdslabs"
password = "sdslabs"
