apiVersion: v1
kind: ConfigMap
metadata:
  name: kashira-config
  namespace: katana
data:
  daemon_port: "{{.DaemonPort}}"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kashira
  namespace: katana
  annotations:
    tick: "false"
spec:
  selector:
    matchLabels:
      app: kashira
  serviceName: kashira-svc
  replicas: 1
  template:
    metadata:
      namespace: katana
      labels:
        app: kashira
    spec:
      serviceAccountName: cluster-admin
      containers:
        - name: kashira
          image: iiteens/kashira
          imagePullPolicy: Always   # added for ease may be remove later
          ports:
            - containerPort: 80
          volumeMounts:
            - name: kashira-data
              mountPath: /opt/kashira/flag-data
          env:
            - name: DAEMON_PORT
              valueFrom:
                configMapKeyRef:
                  name: kashira-config
                  key: daemon_port
  volumeClaimTemplates:
    - metadata:
        name: kashira-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kashira-svc
  namespace: katana
spec:
  selector:
    app: kashira
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
