apiVersion: apps/v1
kind: Deployment
metadata:
  name: katana-broadcast
spec:
  selector:
    matchLabels:
      app: {{.BroadcastLabel}}
  replicas: {{.BroadcastCount}}
  template:
    metadata:
      labels:
        deployment: {{.DeploymentLabel}}
        app: {{.BroadcastLabel}}
    spec:
      containers:
      - name: broadcast
        image: scar26/sdskatanabroadcast:latest
        ports:
        - containerPort:  {{.BroadcastPort}}
        env: 
        - name: "CHALLENGE_ARTIFACT"
          value: {{.ChallengeArtifact}}