kind: ConfigMap
apiVersion: v1
metadata:
  name: teamvm-config
data:
    challenge_dir: {{.ChallengDir}}
    tmp_dir: {{.TempDir}} 
    init_file: {{.InitFile}}
    daemon_port: "{{.DaemonPort}}"
---    
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.TeamPodName}}
spec:
  selector:
    matchLabels:
      app: {{.TeamLabel}}
  template:
    metadata:
      labels:
        app: {{.TeamLabel}}
    spec:
      containers:
      - name: {{.ContainerName}}
        image: percy477/katanad
        env:
          - name: CHALLENGE_DIR 
            valueFrom:
              configMapKeyRef:
                name: teamvm-config          
                key: challenge_dir
          - name: TMP_DIR
            valueFrom:
              configMapKeyRef:
                name: teamvm-config
                key: tmp_dir
          - name: INIT_FILE
            valueFrom:
              configMapKeyRef:
                name: teamvm-config
                key: init_file
          - name: DAEMON_PORT
            valueFrom:
              configMapKeyRef:
                name: teamvm-config
                key: daemon_port       

